<a href="https://colab.research.google.com/github/pavanxk12/Option.strat/blob/main/Dhananiti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

futures = pd.read_csv('/content/drive/MyDrive/Dhaniti/BANKNIFTY_2017_FUTURES.csv')

In [ ]:
columnstocopy=['Date','Time','Close','Contract','Expiry']
res1=futures[columnstocopy].copy()

In [ ]:
res1['Time']=pd.to_datetime(res1['Time'])

In [ ]:
import datetime
desired_time=datetime.time(10,29,59)

In [ ]:
res2=res1[res1['Time'].dt.time==desired_time]
res2=res2[res2['Contract']=='I']
res2.head()

            Date                Time     Close Contract      Expiry
148   2017-01-02 2024-03-11 10:29:59  18067.95        I  2017-01-25
890   2017-01-03 2024-03-11 10:29:59  18107.00        I  2017-01-25
1527  2017-01-04 2024-03-11 10:29:59  18048.05        I  2017-01-25
2186  2017-01-05 2024-03-11 10:29:59  18079.70        I  2017-01-25
2896  2017-01-06 2024-03-11 10:29:59  18340.00        I  2017-01-25

In [ ]:
def roundoff(df_row):
  x = df_row['Close']
  if (x % 100 < 50):
    y = x - x % 100
  elif (x%100>50):
    y=x-x%50
  else:
    y=x
  return y

In [ ]:
value=res2.apply(roundoff,axis=1)

In [ ]:
res2.insert(4,"ATM",value,True)

In [ ]:
res2['Date']=pd.to_datetime(res2['Date'])
res2['Expiry']=pd.to_datetime(res2['Expiry'])

In [ ]:
options=pd.read_csv('/content/drive/MyDrive/Dhaniti/BANKNIFTY_2017_OPTIONS.csv')

In [ ]:
def roundoff1(df_row):
  x = 1.02*df_row['Close']
  if (x % 100 < 50):
    y = x - x % 100
  elif (x%100>50):
    y=x-x%50
  else:
    y=x
  return y

In [ ]:
value1=res2.apply(roundoff1,axis=1)

In [ ]:
res2.insert(4,"OTMCE",value1,True)

In [ ]:
def roundoff2(df_row):
  x = 0.98*df_row['Close']
  if (x % 100 < 50):
    y = x - x % 100
  elif (x%100>50):
    y=x-x%50
  else:
    y=x
  return y

In [ ]:
value2=res2.apply(roundoff2,axis=1)

In [ ]:
res2.insert(4,"OTMPE",value2,True)

In [ ]:
res2.head()

,Date,Time,Close,Contract,OTMPE,OTMCE,ATM,Expiry
148,2017-01-02,2024-03-11 10:29:59,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
890,2017-01-03,2024-03-11 10:29:59,18107.00,I,17700.0,18450.0,18100.0,2017-01-25
1527,2017-01-04,2024-03-11 10:29:59,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
2186,2017-01-05,2024-03-11 10:29:59,18079.70,I,17700.0,18400.0,18050.0,2017-01-25
2896,2017-01-06,2024-03-11 10:29:59,18340.00,I,17950.0,18700.0,18300.0,2017-01-25

In [ ]:
options['Date']=pd.to_datetime(options['Date'])
options['Time']=pd.to_datetime(options['Time'])

In [ ]:
values_todel=['F','V','M']
options=options[~options['Contract_Weekly'].isin(values_todel)]

In [ ]:
options.shape

(4816231, 14)

In [ ]:
import datetime
def extract(res2,date,time):
  date_mask = res2['Date'].isin([date])
  time_mask = res2['Time'].isin([time])

  selected = res2[date_mask & time_mask]

  return selected

Atm for the day on time 10:30.

In [ ]:
date = pd.to_datetime("2017-01-03")
time = pd.to_datetime("10:29:59")
extract(res2,date,time)

,Date,Time,Close,Contract,OTMPE,OTMCE,ATM,Expiry
890,2017-01-03,2024-03-11 10:29:59,18107.0,I,17700.0,18450.0,18100.0,2017-01-25

In [ ]:

merged_data = pd.merge(options, res2, on=['Date', 'Time'])

In [ ]:
merged_data.head()

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
0,BANKNIFTY25JAN1717300PE.NFO,2017-01-02,2024-03-11 10:29:59,124.05,125.85,124.05,125.85,80.0,3200.0,PE,17300.0,2017-01-25,I,IV,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
1,BANKNIFTY05JAN1718800CE.NFO,2017-01-02,2024-03-11 10:29:59,3.85,3.90,3.70,3.90,920.0,109520.0,CE,18800.0,2017-01-05,W,I,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
2,BANKNIFTY25JAN1716300PE.NFO,2017-01-02,2024-03-11 10:29:59,24.55,24.55,22.95,22.95,40.0,33520.0,PE,16300.0,2017-01-25,I,IV,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
3,BANKNIFTY25JAN1716400PE.NFO,2017-01-02,2024-03-11 10:29:59,27.50,27.50,27.50,27.50,1400.0,10160.0,PE,16400.0,2017-01-25,I,IV,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
4,BANKNIFTY25JAN1716500PE.NFO,2017-01-02,2024-03-11 10:29:59,36.35,36.35,36.00,36.00,40.0,107560.0,PE,16500.0,2017-01-25,I,IV,18067.95,I,17700.0,18400.0,18050.0,2017-01-25

In [ ]:
atmdf=merged_data[merged_data['Strike']==merged_data['ATM']]

In [ ]:
atmdf.head()

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
80,BANKNIFTY05JAN1718100CE.NFO,2017-01-03,2024-03-11 10:29:59,86.85,90.60,85.80,90.30,13600.0,368720.0,CE,18100.0,2017-01-05,W,I,18107.00,I,17700.0,18450.0,18100.0,2017-01-25
90,BANKNIFTY05JAN1718100PE.NFO,2017-01-03,2024-03-11 10:29:59,140.95,141.80,136.55,136.55,1160.0,161200.0,PE,18100.0,2017-01-05,W,I,18107.00,I,17700.0,18450.0,18100.0,2017-01-25
100,BANKNIFTY25JAN1718000PE.NFO,2017-01-04,2024-03-11 10:29:59,312.55,313.10,311.00,313.10,160.0,596000.0,PE,18000.0,2017-01-25,I,IV,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
108,BANKNIFTY12JAN1718000CE.NFO,2017-01-04,2024-03-11 10:29:59,205.60,211.00,205.60,211.00,360.0,11160.0,CE,18000.0,2017-01-12,W,II,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
109,BANKNIFTY25JAN1718000CE.NFO,2017-01-04,2024-03-11 10:29:59,362.15,362.55,362.00,362.00,160.0,336960.0,CE,18000.0,2017-01-25,I,IV,18048.05,I,17650.0,18400.0,18000.0,2017-01-25

In [ ]:

otmpedf=merged_data[merged_data['Strike']==merged_data['OTMPE']]
otmpedf = otmpedf[otmpedf['Type']=='PE']

In [ ]:
date = pd.to_datetime("2017-01-05")
time = pd.to_datetime("10:29:59")
extract(otmpedf,date,time)

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
133,BANKNIFTY25JAN1717700PE.NFO,2017-01-05,2024-03-11 10:29:59,181.45,182.2,181.45,182.20,80.0,11520.0,PE,17700.0,2017-01-25,I,IV,18079.7,I,17700.0,18400.0,18050.0,2017-01-25
161,BANKNIFTY05JAN1717700PE.NFO,2017-01-05,2024-03-11 10:29:59,0.35,0.4,0.35,0.35,360.0,540320.0,PE,17700.0,2017-01-05,W,I,18079.7,I,17700.0,18400.0,18050.0,2017-01-25
175,BANKNIFTY12JAN1717700PE.NFO,2017-01-05,2024-03-11 10:29:59,49.55,50.9,49.55,49.55,200.0,34760.0,PE,17700.0,2017-01-12,W,II,18079.7,I,17700.0,18400.0,18050.0,2017-01-25

In [ ]:
otmcedf=merged_data[merged_data['Strike']==merged_data['OTMCE']]
otmcedf=otmcedf[otmcedf['Type']=='CE']
otmcedf.head()

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
16,BANKNIFTY25JAN1718400CE.NFO,2017-01-02,2024-03-11 10:29:59,205.35,205.35,201.00,201.00,40.0,16200.0,CE,18400.0,2017-01-25,I,IV,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
22,BANKNIFTY05JAN1718400CE.NFO,2017-01-02,2024-03-11 10:29:59,25.80,25.95,25.10,25.45,6840.0,329800.0,CE,18400.0,2017-01-05,W,I,18067.95,I,17700.0,18400.0,18050.0,2017-01-25
129,BANKNIFTY05JAN1718400CE.NFO,2017-01-04,2024-03-11 10:29:59,6.50,6.55,6.40,6.40,11400.0,646920.0,CE,18400.0,2017-01-05,W,I,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
140,BANKNIFTY12JAN1718400CE.NFO,2017-01-05,2024-03-11 10:29:59,47.70,47.70,47.35,47.35,160.0,38360.0,CE,18400.0,2017-01-12,W,II,18079.70,I,17700.0,18400.0,18050.0,2017-01-25
144,BANKNIFTY25JAN1718400CE.NFO,2017-01-05,2024-03-11 10:29:59,173.00,173.00,172.00,172.00,120.0,36240.0,CE,18400.0,2017-01-25,I,IV,18079.70,I,17700.0,18400.0,18050.0,2017-01-25

In [ ]:
date = pd.to_datetime("2017-01-06")
time = pd.to_datetime("10:29:59")
extract(atmdf,date,time)

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
197,BANKNIFTY25JAN1718300CE.NFO,2017-01-06,2024-03-11 10:29:59,310.05,312.3,309.00,309.0,200.0,48640.0,CE,18300.0,2017-01-25,I,III,18340.0,I,17950.0,18700.0,18300.0,2017-01-25
211,BANKNIFTY25JAN1718300PE.NFO,2017-01-06,2024-03-11 10:29:59,275.00,275.0,269.95,270.0,240.0,17840.0,PE,18300.0,2017-01-25,I,III,18340.0,I,17950.0,18700.0,18300.0,2017-01-25
239,BANKNIFTY12JAN1718300PE.NFO,2017-01-06,2024-03-11 10:29:59,136.20,137.0,135.05,137.0,2560.0,132840.0,PE,18300.0,2017-01-12,W,I,18340.0,I,17950.0,18700.0,18300.0,2017-01-25
240,BANKNIFTY12JAN1718300CE.NFO,2017-01-06,2024-03-11 10:29:59,130.65,131.8,129.00,129.0,9000.0,349080.0,CE,18300.0,2017-01-12,W,I,18340.0,I,17950.0,18700.0,18300.0,2017-01-25

In [ ]:
atmpedf = atmdf[atmdf['Type']=='PE']
atmpedf.head()

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
90,BANKNIFTY05JAN1718100PE.NFO,2017-01-03,2024-03-11 10:29:59,140.95,141.80,136.55,136.55,1160.0,161200.0,PE,18100.0,2017-01-05,W,I,18107.00,I,17700.0,18450.0,18100.0,2017-01-25
100,BANKNIFTY25JAN1718000PE.NFO,2017-01-04,2024-03-11 10:29:59,312.55,313.10,311.00,313.10,160.0,596000.0,PE,18000.0,2017-01-25,I,IV,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
111,BANKNIFTY12JAN1718000PE.NFO,2017-01-04,2024-03-11 10:29:59,195.95,196.35,195.00,195.00,120.0,22120.0,PE,18000.0,2017-01-12,W,II,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
124,BANKNIFTY05JAN1718000PE.NFO,2017-01-04,2024-03-11 10:29:59,80.00,82.00,79.50,82.00,12640.0,573760.0,PE,18000.0,2017-01-05,W,I,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
211,BANKNIFTY25JAN1718300PE.NFO,2017-01-06,2024-03-11 10:29:59,275.00,275.00,269.95,270.00,240.0,17840.0,PE,18300.0,2017-01-25,I,III,18340.00,I,17950.0,18700.0,18300.0,2017-01-25

In [ ]:
atmcedf = atmdf[atmdf['Type']=='CE']
atmcedf.head()

,Ticker,Date,Time,Open,High,Low,Close_x,Volume,OI,Type,Strike,Expiry_x,Contract_Monthly,Contract_Weekly,Close_y,Contract,OTMPE,OTMCE,ATM,Expiry_y
80,BANKNIFTY05JAN1718100CE.NFO,2017-01-03,2024-03-11 10:29:59,86.85,90.60,85.8,90.30,13600.0,368720.0,CE,18100.0,2017-01-05,W,I,18107.00,I,17700.0,18450.0,18100.0,2017-01-25
108,BANKNIFTY12JAN1718000CE.NFO,2017-01-04,2024-03-11 10:29:59,205.60,211.00,205.6,211.00,360.0,11160.0,CE,18000.0,2017-01-12,W,II,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
109,BANKNIFTY25JAN1718000CE.NFO,2017-01-04,2024-03-11 10:29:59,362.15,362.55,362.0,362.00,160.0,336960.0,CE,18000.0,2017-01-25,I,IV,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
132,BANKNIFTY05JAN1718000CE.NFO,2017-01-04,2024-03-11 10:29:59,96.40,96.95,94.4,94.45,7360.0,546680.0,CE,18000.0,2017-01-05,W,I,18048.05,I,17650.0,18400.0,18000.0,2017-01-25
197,BANKNIFTY25JAN1718300CE.NFO,2017-01-06,2024-03-11 10:29:59,310.05,312.30,309.0,309.00,200.0,48640.0,CE,18300.0,2017-01-25,I,III,18340.00,I,17950.0,18700.0,18300.0,2017-01-25

In [ ]:
atmce = atmcedf[['Ticker','Date','Close_x','Expiry_x','ATM','Type']]
atmce.head()

                          Ticker       Date  Close_x    Expiry_x      ATM Type
80   BANKNIFTY05JAN1718100CE.NFO 2017-01-03    90.30  2017-01-05  18100.0   CE
108  BANKNIFTY12JAN1718000CE.NFO 2017-01-04   211.00  2017-01-12  18000.0   CE
109  BANKNIFTY25JAN1718000CE.NFO 2017-01-04   362.00  2017-01-25  18000.0   CE
132  BANKNIFTY05JAN1718000CE.NFO 2017-01-04    94.45  2017-01-05  18000.0   CE
197  BANKNIFTY25JAN1718300CE.NFO 2017-01-06   309.00  2017-01-25  18300.0   CE

In [ ]:
atmpe = atmpedf[['Ticker','Date','Close_x','Expiry_x','ATM','Type']]
atmpe.head()

                          Ticker       Date  Close_x    Expiry_x      ATM Type
90   BANKNIFTY05JAN1718100PE.NFO 2017-01-03   136.55  2017-01-05  18100.0   PE
100  BANKNIFTY25JAN1718000PE.NFO 2017-01-04   313.10  2017-01-25  18000.0   PE
111  BANKNIFTY12JAN1718000PE.NFO 2017-01-04   195.00  2017-01-12  18000.0   PE
124  BANKNIFTY05JAN1718000PE.NFO 2017-01-04    82.00  2017-01-05  18000.0   PE
211  BANKNIFTY25JAN1718300PE.NFO 2017-01-06   270.00  2017-01-25  18300.0   PE

In [ ]:
otmce = otmcedf[['Ticker','Date','Close_x','Expiry_x','OTMCE','Type']]
otmce.head()

                          Ticker       Date  Close_x    Expiry_x    OTMCE Type
16   BANKNIFTY25JAN1718400CE.NFO 2017-01-02   201.00  2017-01-25  18400.0   CE
22   BANKNIFTY05JAN1718400CE.NFO 2017-01-02    25.45  2017-01-05  18400.0   CE
129  BANKNIFTY05JAN1718400CE.NFO 2017-01-04     6.40  2017-01-05  18400.0   CE
140  BANKNIFTY12JAN1718400CE.NFO 2017-01-05    47.35  2017-01-12  18400.0   CE
144  BANKNIFTY25JAN1718400CE.NFO 2017-01-05   172.00  2017-01-25  18400.0   CE

In [ ]:
otmpe = otmpedf[['Ticker','Date','Close_x','Expiry_x','OTMPE','Type']]
otmpe.head()

                          Ticker       Date  Close_x    Expiry_x    OTMPE Type
30   BANKNIFTY05JAN1717700PE.NFO 2017-01-02    32.35  2017-01-05  17700.0   PE
42   BANKNIFTY25JAN1717700PE.NFO 2017-01-03   192.70  2017-01-25  17700.0   PE
73   BANKNIFTY05JAN1717700PE.NFO 2017-01-03    21.60  2017-01-05  17700.0   PE
133  BANKNIFTY25JAN1717700PE.NFO 2017-01-05   182.20  2017-01-25  17700.0   PE
161  BANKNIFTY05JAN1717700PE.NFO 2017-01-05     0.35  2017-01-05  17700.0   PE

In [ ]:
merged_df = pd.merge(atmce, atmpe, on=['Date', 'Expiry_x'], how='outer', suffixes=('_atmce', '_atmpe'))
merged_df = pd.merge(merged_df, otmce, on=['Date', 'Expiry_x'], how='outer')
merged_df = pd.merge(merged_df, otmpe, on=['Date', 'Expiry_x'], how='outer', suffixes=('_otmce', '_otmpe'))

merged_df['sumclosex'] = merged_df[['Close_x_atmce', 'Close_x_atmpe', 'Close_x_otmce', 'Close_x_otmpe']].sum(axis=1)

merged_df.head()

,Ticker_atmce,Date,Close_x_atmce,Expiry_x,ATM_atmce,Type_atmce,Ticker_atmpe,Close_x_atmpe,ATM_atmpe,Type_atmpe,Ticker_otmce,Close_x_otmce,OTMCE,Type_otmce,Ticker_otmpe,Close_x_otmpe,OTMPE,Type_otmpe,sumclosex
0,BANKNIFTY05JAN1718100CE.NFO,2017-01-03,90.30,2017-01-05,18100.0,CE,BANKNIFTY05JAN1718100PE.NFO,136.55,18100.0,PE,NaN,NaN,NaN,NaN,BANKNIFTY05JAN1717700PE.NFO,21.6,17700.0,PE,248.45
1,BANKNIFTY12JAN1718000CE.NFO,2017-01-04,211.00,2017-01-12,18000.0,CE,BANKNIFTY12JAN1718000PE.NFO,195.00,18000.0,PE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406.00
2,BANKNIFTY25JAN1718000CE.NFO,2017-01-04,362.00,2017-01-25,18000.0,CE,BANKNIFTY25JAN1718000PE.NFO,313.10,18000.0,PE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,675.10
3,BANKNIFTY05JAN1718000CE.NFO,2017-01-04,94.45,2017-01-05,18000.0,CE,BANKNIFTY05JAN1718000PE.NFO,82.00,18000.0,PE,BANKNIFTY05JAN1718400CE.NFO,6.4,18400.0,CE,NaN,NaN,NaN,NaN,182.85
4,BANKNIFTY25JAN1718300CE.NFO,2017-01-06,309.00,2017-01-25,18300.0,CE,BANKNIFTY25JAN1718300PE.NFO,270.00,18300.0,PE,BANKNIFTY25JAN1718700CE.NFO,131.1,18700.0,CE,NaN,NaN,NaN,NaN,710.10

Entry of trade

In [ ]:
result_df = merged_df[['Ticker_atmce','Date', 'Expiry_x', 'sumclosex', 'Ticker_atmpe', 'Ticker_otmce', 'Ticker_otmpe']]

In [ ]:
result_df.head(20)

,Ticker_atmce,Date,Expiry_x,sumclosex,Ticker_atmpe,Ticker_otmce,Ticker_otmpe
0,BANKNIFTY05JAN1718100CE.NFO,2017-01-03,2017-01-05,248.45,BANKNIFTY05JAN1718100PE.NFO,NaN,BANKNIFTY05JAN1717700PE.NFO
1,BANKNIFTY12JAN1718000CE.NFO,2017-01-04,2017-01-12,406.00,BANKNIFTY12JAN1718000PE.NFO,NaN,NaN
2,BANKNIFTY25JAN1718000CE.NFO,2017-01-04,2017-01-25,675.10,BANKNIFTY25JAN1718000PE.NFO,NaN,NaN
3,BANKNIFTY05JAN1718000CE.NFO,2017-01-04,2017-01-05,182.85,BANKNIFTY05JAN1718000PE.NFO,BANKNIFTY05JAN1718400CE.NFO,NaN
4,BANKNIFTY25JAN1718300CE.NFO,2017-01-06,2017-01-25,710.10,BANKNIFTY25JAN1718300PE.NFO,BANKNIFTY25JAN1718700CE.NFO,NaN
5,BANKNIFTY12JAN1718300CE.NFO,2017-01-06,2017-01-12,285.50,BANKNIFTY12JAN1718300PE.NFO,BANKNIFTY12JAN1718700CE.NFO,NaN
6,BANKNIFTY25JAN1718600CE.NFO,2017-01-11,2017-01-25,462.50,BANKNIFTY25JAN1718600PE.NFO,NaN,NaN
7,BANKNIFTY19JAN1718600CE.NFO,2017-01-11,2017-01-19,314.00,BANKNIFTY19JAN1718600PE.NFO,NaN,NaN
8,BANKNIFTY12JAN1718600CE.NFO,2017-01-11,2017-01-12,141.00,BANKNIFTY12JAN1718600PE.NFO,NaN,NaN
9,BANKNIFTY25JAN1718800CE.NFO,2017-01-13,2017-01-25,476.85,BANKNIFTY25JAN1718800PE.NFO,BANKNIFTY25JAN1719200CE.NFO,NaN
10,BANKNIFTY19JAN1718800CE.NFO,2017-01-13,2017-01-19,295.85,BANKNIFTY19JAN1718800PE.NFO,BANKNIFTY19JAN1719200CE.NFO,NaN
11,BANKNIFTY25JAN1719000CE.NFO,2017-01-16,2017-01-25,445.00,BANKNIFTY25JAN1719000PE.NFO,NaN,BANKNIFTY25JAN1718600PE.NFO
12,BANKNIFTY19JAN1719000CE.NFO,2017-01-16,2017-01-19,267.65,BANKNIFTY19JAN1719000PE.NFO,NaN,BANKNIFTY19JAN1718600PE.NFO
13,BANKNIFTY25JAN1719100CE.NFO,2017-01-19,2017-01-25,332.30,BANKNIFTY25JAN1719100PE.NFO,NaN,BANKNIFTY25JAN1718700PE.NFO
14,BANKNIFTY19JAN1719100CE.NFO,2017-01-19,2017-01-19,85.25,BANKNIFTY19JAN1719100PE.NFO,NaN,BANKNIFTY19JAN1718700PE.NFO
15,BANKNIFTY25JAN1719000CE.NFO,2017-01-20,2017-01-25,291.95,BANKNIFTY25JAN1719000PE.NFO,NaN,BANKNIFTY25JAN1718600PE.NFO
16,BANKNIFTY02FEB1719100CE.NFO,2017-01-25,2017-02-02,514.45,BANKNIFTY02FEB1719100PE.NFO,BANKNIFTY02FEB1719500CE.NFO,NaN
17,BANKNIFTY25JAN1719100CE.NFO,2017-01-25,2017-01-25,84.75,BANKNIFTY25JAN1719100PE.NFO,BANKNIFTY25JAN1719500CE.NFO,NaN
18,BANKNIFTY02FEB1719700CE.NFO,2017-01-30,2017-02-02,732.90,BANKNIFTY02FEB1719700PE.NFO,BANKNIFTY02FEB1720100CE.NFO,BANKNIFTY02FEB1719300PE.NFO
19,BANKNIFTY23FEB1719500CE.NFO,2017-01-31,2017-02-23,1073.55,BANKNIFTY23FEB1719500PE.NFO,BANKNIFTY23FEB1719900CE.NFO,NaN

In [ ]:
options.head()

,Ticker,Date,Time,Open,High,Low,Close,Volume,OI,Type,Strike,Expiry,Contract_Monthly,Contract_Weekly
0,BANKNIFTY25JAN1718300CE.NFO,2017-01-02,2024-03-11 09:15:59,311.45,325.0,293.75,293.75,400.0,20040.0,CE,18300.0,2017-01-25,I,IV
1,BANKNIFTY05JAN1718900CE.NFO,2017-01-02,2024-03-11 09:15:59,7.00,12.0,5.75,5.80,2360.0,37160.0,CE,18900.0,2017-01-05,W,I
2,BANKNIFTY05JAN1719000CE.NFO,2017-01-02,2024-03-11 09:15:59,4.40,6.6,4.15,4.20,5680.0,120760.0,CE,19000.0,2017-01-05,W,I
3,BANKNIFTY05JAN1719100CE.NFO,2017-01-02,2024-03-11 09:15:59,3.00,3.0,3.00,3.00,160.0,9960.0,CE,19100.0,2017-01-05,W,I
4,BANKNIFTY05JAN1719500CE.NFO,2017-01-02,2024-03-11 09:15:59,1.50,1.5,1.50,1.50,80.0,24160.0,CE,19500.0,2017-01-05,W,I

In [ ]:
options['Time'] = options['Time'].dt.time
options.head()

,Ticker,Date,Time,Open,High,Low,Close,Volume,OI,Type,Strike,Expiry,Contract_Monthly,Contract_Weekly
0,BANKNIFTY25JAN1718300CE.NFO,2017-01-02,09:15:59,311.45,325.0,293.75,293.75,400.0,20040.0,CE,18300.0,2017-01-25,I,IV
1,BANKNIFTY05JAN1718900CE.NFO,2017-01-02,09:15:59,7.00,12.0,5.75,5.80,2360.0,37160.0,CE,18900.0,2017-01-05,W,I
2,BANKNIFTY05JAN1719000CE.NFO,2017-01-02,09:15:59,4.40,6.6,4.15,4.20,5680.0,120760.0,CE,19000.0,2017-01-05,W,I
3,BANKNIFTY05JAN1719100CE.NFO,2017-01-02,09:15:59,3.00,3.0,3.00,3.00,160.0,9960.0,CE,19100.0,2017-01-05,W,I
4,BANKNIFTY05JAN1719500CE.NFO,2017-01-02,09:15:59,1.50,1.5,1.50,1.50,80.0,24160.0,CE,19500.0,2017-01-05,W,I

In [ ]:
options['Datetime'] = pd.to_datetime(options['Date'].astype(str) + ' ' + options['Time'].astype(str))

In [ ]:
threshold_datetime = pd.to_datetime('2017-01-03 10:29:59')

filtered_df = options[options['Datetime'] > threshold_datetime]

# filtered_df = filtered_df.drop(columns=['Datetime'])

filtered_df.head()

,Ticker,Date,Time,Open,High,Low,Close,Volume,OI,Type,Strike,Expiry,Contract_Monthly,Contract_Weekly,Datetime
23670,BANKNIFTY25JAN1717500PE.NFO,2017-01-03,10:30:59,145.00,145.00,141.35,141.35,1760.0,481840.0,PE,17500.0,2017-01-25,I,IV,2017-01-03 10:30:59
23671,BANKNIFTY25JAN1717800PE.NFO,2017-01-03,10:30:59,221.10,221.10,216.10,216.10,240.0,33280.0,PE,17800.0,2017-01-25,I,IV,2017-01-03 10:30:59
23672,BANKNIFTY25JAN1717800CE.NFO,2017-01-03,10:30:59,516.90,529.75,516.90,529.75,200.0,6240.0,CE,17800.0,2017-01-25,I,IV,2017-01-03 10:30:59
23673,BANKNIFTY25JAN1717600PE.NFO,2017-01-03,10:30:59,167.40,167.40,163.25,163.25,240.0,11360.0,PE,17600.0,2017-01-25,I,IV,2017-01-03 10:30:59
23674,BANKNIFTY25JAN1717900PE.NFO,2017-01-03,10:30:59,257.75,257.75,252.20,252.20,80.0,23320.0,PE,17900.0,2017-01-25,I,IV,2017-01-03 10:30:59

In [ ]:
ticker_columns = ['Ticker_atmce', 'Ticker_atmpe', 'Ticker_otmce', 'Ticker_otmpe']

ticker_variables = {}

for col in ticker_columns:
    ticker_variables[col] = result_df[col].fillna('').tolist()

In [ ]:
import pandas as pd
import numpy as np

desired_time = pd.to_datetime('2017-01-03 10:29:59')
sum_closex = result_df['sumclosex'].iloc[0]
total_close_sums = []


max_length = max(filtered_df.groupby('Ticker')['Close'].count())

for i in range(max_length):
    close_values_sum = 0

    for col in ticker_columns:
        key = ticker_variables[col][0]
        a = filtered_df[filtered_df['Ticker'] == key]

        if not a.empty and i < len(a):
            close_values_sum += a['Close'].iloc[i]
            # print("Close value for {} after {} at index {}: {}".format(key, desired_time, i, a['Close'].iloc[i]))

    if close_values_sum == 0:
        break

    print("\nSum: ", close_values_sum)
    total_close_sums.append(close_values_sum)

    if close_values_sum <= 0.2 * sum_closex:
        print("Yes")
        break
    elif close_values_sum > 1.3 * sum_closex:
        print("No")
        break

# total_close_sums_array = np.array(total_close_sums)

# print("\nTotal Close Sums Array after {}: {}".format(desired_time, total_close_sums_array))

Sum:  247.4

Sum:  248.40000000000003

Sum:  246.79999999999998

Sum:  248.45000000000002

Sum:  248.75

Sum:  243.85000000000002

Sum:  245.15

Sum:  243.3

Sum:  243.5

Sum:  242.9

Sum:  244.60000000000002

Sum:  246.45

Sum:  247.24999999999997

Sum:  246.85

Sum:  247.65

Sum:  245.55

Sum:  246.6

Sum:  245.1

Sum:  243.65

Sum:  243.20000000000002

Sum:  244.5

Sum:  245.3

Sum:  245.1

Sum:  246.95

Sum:  248.54999999999998

Sum:  246.5

Sum:  246.10000000000002

Sum:  248.14999999999998

Sum:  247.35

Sum:  245.1

Sum:  245.8

Sum:  245.05

Sum:  244.89999999999998

Sum:  245.25

Sum:  243.85

Sum:  241.45000000000002

Sum:  241.79999999999998

Sum:  242.20000000000002

Sum:  242.89999999999998

Sum:  245.1

Sum:  245.60000000000002

Sum:  245.55

Sum:  242.35

Sum:  242.85

Sum:  243.75

Sum:  243.0

Sum:  243.1

Sum:  243.85

Sum:  243.35000000000002

Sum:  242.54999999999998

Sum:  243.1

Sum:  241.34999999999997

Sum:  241.64999999999998

Sum:  242.20000000000002

Sum:  241.89999999999998

Sum:  241.29999999999998

Sum:  240.3

Sum:  239.7

Sum:  240.35

Sum:  241.29999999999998

Sum:  241.9

Sum:  239.6

Sum:  239.20000000000002

Sum:  239.95

Sum:  242.0

Sum:  242.75

Sum:  240.20000000000002

Sum:  241.20000000000002

Sum:  242.0

Sum:  242.3

Sum:  243.0

Sum:  242.9

Sum:  243.6

Sum:  244.5

Sum:  242.3

Sum:  241.15

Sum:  245.65

Sum:  244.59999999999997

Sum:  248.65

Sum:  247.95

Sum:  247.15

Sum:  246.75000000000003

Sum:  241.0

Sum:  241.65

Sum:  241.7

Sum:  241.90000000000003

Sum:  243.15

Sum:  244.2

Sum:  243.9

Sum:  245.4

Sum:  242.40000000000003

Sum:  241.60000000000002

Sum:  242.5

Sum:  242.85000000000002

Sum:  242.9

Sum:  240.7

Sum:  242.0

Sum:  239.35000000000002

Sum:  239.6

Sum:  239.0

Sum:  238.55

Sum:  240.15

Sum:  240.5

Sum:  240.05

Sum:  241.45000000000002

Sum:  241.25

Sum:  241.5

Sum:  239.95000000000002

Sum:  237.65

Sum:  238.55

Sum:  237.45

Sum:  238.5

Sum:  239.04999999999998

Sum:  236.55

Sum:  239.05

Sum:  236.9

Sum:  235.5

Sum:  234.3

Sum:  235.0

Sum:  234.85

Sum:  233.0

Sum:  234.54999999999998

Sum:  234.35

Sum:  234.39999999999998

Sum:  234.29999999999998

Sum:  234.70000000000002

Sum:  234.0

Sum:  233.95

Sum:  234.6

Sum:  233.79999999999998

Sum:  238.35000000000002

Sum:  234.89999999999998

Sum:  238.35

Sum:  237.2

Sum:  237.65

Sum:  236.9

Sum:  237.55

Sum:  238.10000000000002

Sum:  238.95000000000002

Sum:  237.0

Sum:  238.25

Sum:  236.29999999999998

Sum:  238.8

Sum:  238.20000000000002

Sum:  235.15000000000003

Sum:  236.10000000000002

Sum:  236.20000000000002

Sum:  235.8

Sum:  236.05

Sum:  236.4

Sum:  235.6

Sum:  234.65

Sum:  234.10000000000002

Sum:  234.6

Sum:  235.70000000000002

Sum:  236.5

Sum:  237.15

Sum:  236.40000000000003

Sum:  235.25

Sum:  233.5

Sum:  233.6

Sum:  237.55

Sum:  237.95

Sum:  236.5

Sum:  236.99999999999997

Sum:  238.25

Sum:  256.15

Sum:  271.95

Sum:  263.1

Sum:  269.3

Sum:  277.7

Sum:  277.35

Sum:  274.9

Sum:  286.05

Sum:  283.65

Sum:  282.4

Sum:  274.2

Sum:  266.0

Sum:  256.40000000000003

Sum:  261.05

Sum:  266.3

Sum:  265.15

Sum:  268.90000000000003

Sum:  268.55

Sum:  262.6

Sum:  264.9

Sum:  268.84999999999997

Sum:  267.55

Sum:  268.85

Sum:  270.85

Sum:  272.75

Sum:  275.7

Sum:  280.2

Sum:  280.55

Sum:  276.65

Sum:  271.7

Sum:  269.5

Sum:  267.55

Sum:  267.6

Sum:  264.75

Sum:  254.10000000000002

Sum:  246.35000000000002

Sum:  247.35

Sum:  250.45

Sum:  252.15

Sum:  251.29999999999998

Sum:  250.9

Sum:  253.70000000000002

Sum:  252.25

Sum:  247.70000000000002

Sum:  248.0

Sum:  248.95000000000002

Sum:  247.5

Sum:  247.65

Sum:  245.7

Sum:  241.10000000000002

Sum:  243.85

Sum:  246.00000000000003

Sum:  247.25

Sum:  248.9

Sum:  249.99999999999997

Sum:  250.89999999999998

Sum:  251.9

Sum:  251.4

Sum:  247.45

Sum:  245.7

Sum:  243.7

Sum:  245.35

Sum:  244.25

Sum:  243.5

Sum:  243.45000000000002

Sum:  245.20000000000002

Sum:  244.45000000000002

Sum:  246.2

Sum:  246.35

Sum:  244.89999999999998

Sum:  244.45000000000002

Sum:  241.6

Sum:  235.95

Sum:  236.64999999999998

Sum:  233.3

Sum:  228.2

Sum:  227.1

Sum:  228.04999999999998

Sum:  228.2

Sum:  229.1

Sum:  225.5

Sum:  227.79999999999998

Sum:  228.5

Sum:  229.5

Sum:  226.95000000000002

Sum:  224.99999999999997

Sum:  224.9

Sum:  222.25

Sum:  222.8

Sum:  219.5

Sum:  218.25

Sum:  218.35

Sum:  219.7

Sum:  218.05

Sum:  220.75

Sum:  221.3

Sum:  221.15

Sum:  223.1

Sum:  223.25

Sum:  222.45

Sum:  220.9

Sum:  220.6

Sum:  220.4

Sum:  222.54999999999998

Sum:  224.14999999999998

Sum:  223.35000000000002

Sum:  220.7

Sum:  221.35000000000002

Sum:  225.75

Sum:  223.89999999999998

Sum:  221.65

Sum:  218.8

Sum:  220.8

Sum:  224.60000000000002

Sum:  224.05

Sum:  224.35

Sum:  225.15

Sum:  226.10000000000002

Sum:  225.4

Sum:  224.0

Sum:  224.95

Sum:  224.54999999999998

Sum:  225.5

Sum:  225.79999999999998

Sum:  227.20000000000002

Sum:  227.3

Sum:  225.5

Sum:  225.64999999999998

Sum:  225.35

Sum:  223.20000000000002

Sum:  219.45000000000002

Sum:  215.55

Sum:  213.35

Sum:  214.59999999999997

Sum:  205.35000000000002

Sum:  194.7

Sum:  204.79999999999998

Sum:  206.65

Sum:  198.25

Sum:  195.1

Sum:  196.15000000000003

Sum:  209.1

Sum:  201.4

Sum:  205.85

Sum:  200.55

Sum:  197.75

Sum:  200.54999999999998

Sum:  203.2

Sum:  205.34999999999997

Sum:  197.15000000000003

Sum:  202.95000000000002

Sum:  193.6

Sum:  201.29999999999998

Sum:  213.64999999999998

Sum:  229.49999999999997

Sum:  215.15

Sum:  209.79999999999998

Sum:  217.70000000000002

Sum:  210.95000000000002

Sum:  214.5

Sum:  223.6

Sum:  208.4

Sum:  212.15

Sum:  216.45000000000002

Sum:  213.7

Sum:  201.20000000000002

Sum:  205.0

Sum:  205.65

Sum:  206.05

Sum:  198.4

Sum:  196.29999999999998

Sum:  197.95000000000002

Sum:  205.65

Sum:  198.2

Sum:  198.70000000000002

Sum:  202.04999999999998

Sum:  198.5

Sum:  204.00000000000003

Sum:  201.75

Sum:  196.6

Sum:  202.15

Sum:  199.79999999999998

Sum:  199.35

Sum:  197.2

Sum:  199.35

Sum:  205.10000000000002

Sum:  205.4

Sum:  204.85

Sum:  203.95

Sum:  197.8

Sum:  205.75

Sum:  202.4

Sum:  200.1

Sum:  200.4

Sum:  197.79999999999998

Sum:  200.85

Sum:  205.6

Sum:  204.4

Sum:  204.10000000000002

Sum:  202.55

Sum:  205.1

Sum:  203.75

Sum:  205.35

Sum:  208.7

Sum:  205.5

Sum:  209.05

Sum:  202.2

Sum:  201.35

Sum:  204.2

Sum:  208.75

Sum:  212.14999999999998

Sum:  210.05

Sum:  203.5

Sum:  208.25

Sum:  207.9

Sum:  208.1

Sum:  207.25

Sum:  202.60000000000002

Sum:  209.7

Sum:  218.14999999999998

Sum:  213.45000000000002

Sum:  217.15

Sum:  225.20000000000002

Sum:  225.6

Sum:  231.55

Sum:  232.35

Sum:  224.15000000000003

Sum:  223.5

Sum:  217.75

Sum:  218.8

Sum:  211.59999999999997

Sum:  211.95

Sum:  214.75

Sum:  214.5

Sum:  210.75

Sum:  219.55

Sum:  219.65

Sum:  220.95

Sum:  222.1

Sum:  219.5

Sum:  220.4

Sum:  223.25

Sum:  222.15

Sum:  217.45

Sum:  214.45

Sum:  214.1

Sum:  213.35

Sum:  213.5

Sum:  212.85

Sum:  212.55

Sum:  213.5

Sum:  211.79999999999998

Sum:  214.7

Sum:  211.8

Sum:  212.89999999999998

Sum:  202.85

Sum:  202.1

Sum:  201.10000000000002

Sum:  189.45

Sum:  197.35

Sum:  201.55

Sum:  196.85

Sum:  196.2

Sum:  198.4

Sum:  203.3

Sum:  196.55

Sum:  198.85

Sum:  202.45

Sum:  200.95

Sum:  197.95

Sum:  205.7

Sum:  201.3

Sum:  221.50000000000003

Sum:  205.65

Sum:  210.15

Sum:  209.8

Sum:  204.9

Sum:  210.3

Sum:  206.1

Sum:  211.15

Sum:  207.05

Sum:  210.04999999999998

Sum:  208.64999999999998

Sum:  213.29999999999998

Sum:  215.15000000000003

Sum:  221.85

Sum:  216.59999999999997

Sum:  219.6

Sum:  218.8

Sum:  221.54999999999998

Sum:  216.39999999999998

Sum:  216.70000000000002

Sum:  213.45

Sum:  211.04999999999998

Sum:  216.10000000000002

Sum:  214.65

Sum:  214.20000000000002

Sum:  215.64999999999998

Sum:  218.2

Sum:  227.45

Sum:  220.4

Sum:  222.5

Sum:  235.3

Sum:  224.25

Sum:  227.45

Sum:  222.45000000000002

Sum:  221.70000000000002

Sum:  224.0

Sum:  222.95

Sum:  227.4

Sum:  233.4

Sum:  232.74999999999997

Sum:  228.9

Sum:  225.85

Sum:  227.3

Sum:  217.9

Sum:  213.9

Sum:  209.3

Sum:  216.55

Sum:  213.95000000000002

Sum:  210.60000000000002

Sum:  211.8

Sum:  209.75000000000003

Sum:  207.9

Sum:  206.7

Sum:  210.55

Sum:  210.54999999999998

Sum:  214.5

Sum:  208.65

Sum:  212.65

Sum:  208.85

Sum:  209.9

Sum:  210.65

Sum:  208.14999999999998

Sum:  207.75

Sum:  209.2

Sum:  211.54999999999998

Sum:  212.0

Sum:  207.3

Sum:  210.6

Sum:  214.5

Sum:  215.4

Sum:  215.3

Sum:  211.14999999999998

Sum:  211.35000000000002

Sum:  213.2

Sum:  212.95000000000002

Sum:  215.45

Sum:  214.85000000000002

Sum:  211.70000000000002

Sum:  215.75

Sum:  213.15

Sum:  211.95

Sum:  212.10000000000002

Sum:  206.7

Sum:  208.5

Sum:  209.65

Sum:  213.49999999999997

Sum:  212.95

Sum:  207.25000000000003

Sum:  208.1

Sum:  208.35000000000002

Sum:  194.20000000000002

Sum:  195.75000000000003

Sum:  193.70000000000002

Sum:  196.95

Sum:  200.14999999999998

Sum:  192.15

Sum:  195.54999999999998

Sum:  197.85

Sum:  197.04999999999998

Sum:  197.45000000000002

Sum:  196.29999999999998

Sum:  204.45

Sum:  204.5

Sum:  201.1

Sum:  202.7

Sum:  202.2

Sum:  203.14999999999998

Sum:  208.7

Sum:  202.55

Sum:  204.35

Sum:  200.7

Sum:  196.4

Sum:  194.85

Sum:  199.5

Sum:  197.75

Sum:  201.54999999999998

Sum:  198.45

Sum:  197.35000000000002

Sum:  202.4

Sum:  200.85

Sum:  199.3

Sum:  195.8

Sum:  202.85

Sum:  196.2

Sum:  195.6

Sum:  199.09999999999997

Sum:  196.25

Sum:  200.75000000000003

Sum:  202.65000000000003

Sum:  204.35000000000002

Sum:  201.9

Sum:  200.45

Sum:  203.4

Sum:  200.29999999999998

Sum:  209.75

Sum:  204.90000000000003

Sum:  202.25

Sum:  207.45

Sum:  203.8

Sum:  203.45

Sum:  214.4

Sum:  219.65

Sum:  211.89999999999998

Sum:  217.00000000000003

Sum:  212.25

Sum:  216.25000000000003

Sum:  212.9

Sum:  209.0

Sum:  225.85

Sum:  219.5

Sum:  229.10000000000002

Sum:  230.2

Sum:  218.05

Sum:  217.0

Sum:  209.85000000000002

Sum:  200.45

Sum:  210.5

Sum:  210.5

Sum:  205.1

Sum:  205.65

Sum:  205.55

Sum:  213.95

Sum:  212.25

Sum:  210.65

Sum:  211.7

Sum:  215.95

Sum:  215.45000000000002

Sum:  223.25

Sum:  222.45

Sum:  208.20000000000002

Sum:  213.95

Sum:  213.7

Sum:  211.05

Sum:  210.04999999999998

Sum:  207.1

Sum:  211.6

Sum:  208.5

Sum:  206.5

Sum:  204.2

Sum:  202.04999999999998

Sum:  204.65

Sum:  206.4

Sum:  218.45

Sum:  217.0

Sum:  228.85

Sum:  218.79999999999998

Sum:  221.2

Sum:  218.8

Sum:  223.25

Sum:  207.8

Sum:  208.75

Sum:  215.85000000000002

Sum:  224.3

Sum:  219.10000000000002

Sum:  234.9

Sum:  224.15

Sum:  220.5

Sum:  225.45000000000002

Sum:  240.60000000000002

Sum:  229.85

Sum:  227.85

Sum:  228.6

Sum:  234.10000000000002

Sum:  226.05

Sum:  229.20000000000002

Sum:  232.15

Sum:  227.55

Sum:  215.25

Sum:  223.0

Sum:  225.3

Sum:  224.35

Sum:  227.2

Sum:  225.25

Sum:  224.35000000000002

Sum:  227.04999999999998

Sum:  227.05

Sum:  227.05

Sum:  219.14999999999998

Sum:  218.7

Sum:  225.20000000000002

Sum:  225.45

Sum:  222.75

Sum:  231.75000000000003

Sum:  225.95

Sum:  227.45

Sum:  219.35000000000002

Sum:  215.65

Sum:  227.95

Sum:  227.70000000000002

Sum:  230.75

Sum:  224.55

Sum:  226.9

Sum:  225.3

Sum:  224.4

Sum:  218.35

Sum:  220.05

Sum:  218.15

Sum:  216.5

Sum:  134.39999999999998

Sum:  125.55

Sum:  138.9

Sum:  134.25

Sum:  131.15

Sum:  125.7

Sum:  123.94999999999999

Sum:  122.05

Sum:  124.5

Sum:  122.4

Sum:  115.3

Sum:  118.35

Sum:  114.65

Sum:  114.55

Sum:  118.35

Sum:  109.65

Sum:  110.0

Sum:  108.9

Sum:  104.1

Sum:  103.25

Sum:  102.8

Sum:  103.3

Sum:  104.95

Sum:  105.15

Sum:  103.65

Sum:  104.2

Sum:  103.35000000000001

Sum:  103.55000000000001

Sum:  103.5

Sum:  100.25

Sum:  100.8

Sum:  100.4

Sum:  99.4

Sum:  100.64999999999999

Sum:  101.45

Sum:  101.44999999999999

Sum:  101.44999999999999

Sum:  100.4

Sum:  102.25

Sum:  98.89999999999999

Sum:  99.2

Sum:  99.44999999999999

Sum:  100.35

Sum:  101.35000000000001

Sum:  99.44999999999999

Sum:  98.0

Sum:  98.6

Sum:  98.95

Sum:  102.19999999999999

Sum:  100.5

Sum:  101.8

Sum:  103.3

Sum:  102.6

Sum:  101.75

Sum:  100.0

Sum:  100.85

Sum:  99.3

Sum:  100.3

Sum:  104.3

Sum:  101.35000000000001

Sum:  103.19999999999999

Sum:  102.15

Sum:  105.20000000000002

Sum:  104.45

Sum:  106.15

Sum:  103.1

Sum:  100.1

Sum:  101.19999999999999

Sum:  99.94999999999999

Sum:  99.54999999999998

Sum:  98.3

Sum:  98.80000000000001

Sum:  97.2

Sum:  99.2

Sum:  99.45

Sum:  99.35

Sum:  100.1

Sum:  99.65

Sum:  99.75

Sum:  98.05000000000001

Sum:  96.4

Sum:  97.75

Sum:  98.4

Sum:  99.5

Sum:  101.1

Sum:  100.85000000000001

Sum:  100.05

Sum:  99.85

Sum:  101.19999999999999

Sum:  98.60000000000001

Sum:  97.29999999999998

Sum:  95.6

Sum:  95.85

Sum:  94.44999999999999

Sum:  93.15

Sum:  92.74999999999999

Sum:  92.1

Sum:  93.55

Sum:  94.0

Sum:  93.35

Sum:  96.14999999999999

Sum:  96.15

Sum:  94.60000000000001

Sum:  93.25

Sum:  95.64999999999999

Sum:  94.74999999999999

Sum:  96.7

Sum:  97.14999999999999

Sum:  96.55

Sum:  95.39999999999999

Sum:  96.89999999999999

Sum:  95.55

Sum:  95.64999999999999

Sum:  95.35

Sum:  94.69999999999999

Sum:  95.89999999999999

Sum:  95.5

Sum:  94.9

Sum:  94.9

Sum:  95.0

Sum:  92.9

Sum:  92.44999999999999

Sum:  90.85

Sum:  91.75

Sum:  90.3

Sum:  90.65

Sum:  84.85000000000001

Sum:  82.9

Sum:  84.85

Sum:  85.55000000000001

Sum:  84.95

Sum:  87.45

Sum:  86.39999999999999

Sum:  87.05

Sum:  86.25000000000001

Sum:  86.4

Sum:  86.5

Sum:  85.35000000000001

Sum:  86.6

Sum:  86.3

Sum:  87.35000000000001

Sum:  88.55

Sum:  88.5

Sum:  87.9

Sum:  87.65

Sum:  85.25

Sum:  80.75

Sum:  82.45

Sum:  84.4

Sum:  85.05

Sum:  84.15

Sum:  81.15

Sum:  80.9

Sum:  79.55000000000001

Sum:  79.45

Sum:  76.95

Sum:  76.25

Sum:  74.05

Sum:  72.65

Sum:  74.79999999999998

Sum:  74.4

Sum:  71.64999999999999

Sum:  71.7

Sum:  72.0

Sum:  72.95

Sum:  73.25

Sum:  71.95

Sum:  71.35

Sum:  70.39999999999999

Sum:  69.7

Sum:  69.55

Sum:  69.2

Sum:  69.94999999999999

Sum:  70.19999999999999

Sum:  71.25

Sum:  71.15

Sum:  69.60000000000001

Sum:  69.80000000000001

Sum:  68.4

Sum:  68.85000000000001

Sum:  68.75

Sum:  68.3

Sum:  67.69999999999999

Sum:  69.29999999999998

Sum:  70.44999999999999

Sum:  67.85

Sum:  67.65

Sum:  68.65

Sum:  68.44999999999999

Sum:  70.10000000000001

Sum:  70.6

Sum:  69.69999999999999

Sum:  68.69999999999999

Sum:  69.0

Sum:  70.15

Sum:  69.75

Sum:  70.3

Sum:  70.14999999999999

Sum:  69.25

Sum:  69.14999999999999

Sum:  69.2

Sum:  68.2

Sum:  69.4

Sum:  67.3

Sum:  67.75

Sum:  65.19999999999999

Sum:  65.69999999999999

Sum:  66.10000000000001

Sum:  66.8

Sum:  66.75

Sum:  66.55

Sum:  66.30000000000001

Sum:  67.10000000000001

Sum:  68.0

Sum:  67.0

Sum:  67.05000000000001

Sum:  64.25

Sum:  63.15

Sum:  64.64999999999999

Sum:  64.80000000000001

Sum:  64.64999999999999

Sum:  64.45

Sum:  63.300000000000004

Sum:  62.449999999999996

Sum:  61.9

Sum:  61.550000000000004

Sum:  60.300000000000004

Sum:  60.75000000000001

Sum:  59.35

Sum:  59.85

Sum:  60.4

Sum:  59.099999999999994

Sum:  58.449999999999996

Sum:  57.6

Sum:  58.849999999999994

Sum:  57.85

Sum:  58.75

Sum:  57.6

Sum:  56.65

Sum:  57.15

Sum:  56.65

Sum:  56.2

Sum:  56.85

Sum:  56.9

Sum:  56.099999999999994

Sum:  54.4

Sum:  55.55

Sum:  55.25

Sum:  55.099999999999994

Sum:  54.449999999999996

Sum:  51.199999999999996

Sum:  51.949999999999996

Sum:  51.14999999999999

Sum:  52.15

Sum:  51.5

Sum:  51.45

Sum:  50.5

Sum:  51.349999999999994

Sum:  49.3
Yes